### ISSUE TITLE
Sanity V3 - Roadmap ?

### ISSUE THREAD

**Issue by chihabhajji** [fedeya/next-auth-sanity#15]
i havent taken a look at the code base yet, but how can we make this work with Sanity V3 ?

**Comment by Fedeya** [comment]
this should work with sanity v3, internally this just performs data fetching/mutations with the `@sanity/client`
if groq or @sanity/client doesn't change this doesn't need a big update  

i released a new version today, the issues with the latest `@sanity/client` and `next-auth` version should be fixed 
but in any update of the `@sanity/client` the types are broken is necessary think how to fix it to keep this "unbroken"
