### ISSUE TITLE
Sign up with existing email throws error

### ISSUE THREAD

**Issue by dhatGuy** [fedeya/next-auth-sanity#40]
When I try to register a user with an email that is already taken, it throws a server error.

![image](https://github.com/fedeya/next-auth-sanity/assets/51405947/c66aa513-8e2c-4dcf-844f-4d84a943bde6)

Repo: https://github.com/feyiamujo1/upland-rice-app

**Comment by fedeya** [comment]
Hi @dhatGuy! this should be fixed in the latest version, can you check again?

**Comment by dhatGuy** [comment]
Yes, works fine now. Thanks
