### ISSUE TITLE
Throw error

### ISSUE THREAD

**Issue by axelverglas** [fedeya/next-auth-sanity#43]
I can't show errors on my signUp page please help me 
 const onSubmit: SubmitHandler<SignUpFormInputs> = async data => {
    const { email, password, name } = data;

    try {
      const user = await signUp({
        email,
        password,
        name,
      });
      console.log(user);

      const res = await signIn('sanity-login', {
        redirect: false,
        email,
        password,
      });

      if (res?.error) {
        console.log(res);
        toast.error(res.error);
        return;
      }

      router.push('/');
    } catch (error) {
      console.log(error);

      toast.error('Something went wrong. Please try again later.');
    }
  };

**Comment by fedeya** [comment]
Hi @axelverglas! now in the latest version the lib throw errors, this should be fixed
