### ISSUE TITLE
Any plan to make next-auth-sanity to be compatible with Next Auth v4?

### ISSUE THREAD

**Issue by AeroFiTech** [Fedeya/next-auth-sanity#7]
Hi Fedeya,

Wishing you well and happy new year!

Since Next Auth was updated to v4 last month (I think) which has some breaking changes, do you have any plan to update this library as well to be compatible with Next Auth v4?

I encountered some error using the next-auth-sanity library with next-auth v4.

Cheers mate.

**Comment by danielvanc** [comment]
Yeah I've just encountered errors on next-auth v4 as well. Unusable while it errors, unfortunately. Here's what I'm getting @kmelve @Fedeya 

<img width="842" alt="Screenshot 2022-01-10 at 20 22 54" src="https://user-images.githubusercontent.com/310698/148834027-2dc4b9a4-a09c-49c4-9a0e-3e4495b5171d.png">

**Comment by Fedeya** [comment]
Hello @danielvanc @AeroFiTech in this days i see the changes on next auth and update the library, any pr is welcome!

**Comment by Fedeya** [comment]
already make the changes, all works without failures!, i only need to update the docs for the merge

**Comment by danielvanc** [comment]
Awesome, thank you for the speedy fix @Fedeya ! 🥇

**Comment by dshcheung** [comment]
@Fedeya any news on the merge? I see that the PR is ready but have not been merged.

**Comment by Fedeya** [comment]
> @Fedeya any news on the merge? I see that the PR is ready but have not been merged.

sorry i forgot to do the docs, i already made that and merge and publish to npm

**Comment by AeroFiTech** [comment]
@Fedeya Awesome.. Let me have a spin on this soon! You're the best!
